name = "jisp"
uuid = "5ef860f4-d5f4-4594-87a9-91908b30ff96"
version = "0.1.0"
authors = ["Lorenzo <lorenzobaracco01@gmail.com>"]

[deps]
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"

[compat]
Infiltrator = "1.9.11"
